[build-system]
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 3.1.0, <4",
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py36"]
line-length = 119

[tool.isort]
line_length=119
